name: Release Crates

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

env:
  STORE_PATH: ''

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write
  packages: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: jfrog-fastci/fastci@v0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          create_issues_from_insights: "true"
          accept_terms: "yes"

      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: dtolnay/rust-toolchain@stable

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y libwebkit2gtk-4.1-dev

      - name: Login to crates.io
        run: |
          echo ${{ secrets.CRATES_IO_API_TOKEN }} | cargo login

      # TODO: cargo publish --workspace is still experimental
      - name: Crates publish
        run: |
          cargo publish -p tauri-plugin-mcp
